### ISSUE TITLE
 CMAN Archive

### ISSUE THREAD

**Issue by LewisTehMinerz** [Comprehensive-Minecraft-Archive-Network/CMAN-Archive#1]
Will, I don't think modders will agree to putting their mods on this site, unless it's just JSON files?

**Comment by williambl** [comment]
It's just JSON files, with stuff like version numbers and where the link is.
I also made a badge, if they want to show that their mod is indexed:
https://img.shields.io/badge/CMAN-Indexed-green.svg

**Comment by LewisTehMinerz** [comment]
I quickly made a modification to it, so it looks a bit more metro.

**Comment by williambl** [comment]
TL;DR: Aaaah squares...

The square one wouldn't really fit in with a forum post though, being really flat. I mean, it would fit in the windows 8/8.1/10/84.10^5 start screen (urgh), but not really in a forum post. (It would if it had rounded corners, but it doesn't...)

**Comment by LewisTehMinerz** [comment]
Hmmm... okay, remove the ?<blah> bit from it and it's all okay. I'm just making teams currently.

**Comment by williambl** [comment]
Quick thing: What do you mean 'the ? bit'?

**Comment by LewisTehMinerz** [comment]
You know where the .svg on the URL is? It's the ? and all the stuff after I'm talking about (e.g. something.svg?test, you would remove ?test so it's just something.svg.)

**Comment by williambl** [comment]
OK.
